Nm/import seed
bloxapp/blox-live pull request #101
Opened 2021-01-24 16:38 UTC by meshin-blox

Subjects to test:

1. Select import button
2. Put seed in textarea and set password
3. Generated validators appear in the table

2021-01-24 16:42 UTC, meshin-blox commented on app/backend/proccess-manager/import-validators.process.ts
> +    // TODO: what is the prefix for db?
Issue #1 - make network not hardcoded

2021-01-24 16:43 UTC, meshin-blox commented on app/backend/services/key-manager/key-manager.service.ts
> +      console.log(`${this.executablePath} wallet account create --seed=${seed} --index=${index} --network=${network} --accumulate=true --highest-source=${highestSource} --highest-target=${highestTarg
remove

2021-01-24 16:44 UTC, meshin-blox commented on app/components/Wizard/components/Validators/ImportValidators/ImportValidators.tsx
> +            isPagination
Fix pagination, it is not working right now, just shows inactive links

2021-01-24 16:45 UTC, meshin-blox commented on app/components/Wizard/components/common/Button/Button.js
> +  box-shadow: ${({ theme, isDisabled, border}) => border ? (isDisabled ? `${theme.gray600} inset 0px 0px 0px 1px`
`isDisabled` passed as styled component prop?

2021-01-24 16:45 UTC, meshin-blox commented on app/components/Wizard/components/common/Template/Navigation/Navigation.tsx
> +  console.log('TEST STEP ----', step)
remove

2021-01-24 16:46 UTC, meshin-blox commented on app/package.json
> +  "version": "1.4.0-dev.2",
Conflict in PR here

2021-01-24 16:46 UTC, meshin-blox commented on tsconfig.json
> +    "typeRoots": ["app/types/*.d.ts"]
Even when this type is added, WebStorm still highlighting all svg imports with red, need to fix in future

2021-01-24 16:53 UTC, nivBlox commented on app/assets/images/arrow-forward.svg
> +    </defs>
@meshin-blox Are you using icons as font?

2021-01-25 15:54 UTC, meshin-blox commented on app/components/Wizard/components/Validators/ImportValidators/components/ImportedValidatorsList.tsx
> +
Here should run process of saving all validators in keyvault mnager and then creating blox account

2021-01-27 10:22 UTC, meshin-blox commented on app/assets/images/arrow-forward.svg
> +    </defs>
@nivBlox no this is just an image displaying tooltip on hover

2021-02-02 09:09 UTC, olegshmuelov commented on app/components/Wizard/components/Validators/ImportValidators/components/ImportedValidatorsList.tsx
> +          validators.length
here should be passed validators.length-1
indicating till which index should be imported

2021-02-02 09:20 UTC, olegshmuelov commented on app/backend/proccess-manager/account-create.process.ts
> +  constructor(network: string, accountsNumber?: number) {
I suggest rename this param to indexToRestore

2021-02-02 09:22 UTC, olegshmuelov commented on app/backend/proccess-manager/account-create.process.ts
> +          getNextIndex: !accountsNumber,
check indexToRestore for undefined 
indexToRestore == null
https://stackoverflow.com/questions/28975896/is-there-a-way-to-check-for-both-null-and-undefined

2021-02-02 09:22 UTC, olegshmuelov commented on app/backend/proccess-manager/account-create.process.ts
> +          indexToRestore: accountsNumber ? accountsNumber - 1 : 0
pass indexToRestore as is

2021-02-02 09:23 UTC, olegshmuelov commented on app/backend/proccess-manager/account-create.process.ts
> +          accountsNumber
pass indexToRestore as is

2021-02-02 09:27 UTC, olegshmuelov commented on app/backend/services/account/account.service.ts
> +  async createBloxAccounts({ accountsNumber }: { accountsNumber?: number }): Promise<any> {
rename accountsNumber param to indexToRestore

2021-02-02 09:30 UTC, olegshmuelov commented on app/backend/services/account/account.service.ts
> +    }
use nullish-coalescing
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing
const index: number =  indexToRestore  ?? +Connection.db(this.storePrefix).get(`index.${network}`) + 1;

2021-02-02 09:50 UTC, olegshmuelov commented on app/backend/services/account/account.service.ts
>      const index: number = getNextIndex ? await this.getNextIndex(network) : indexToRestore;
lets do refactoring here as well as in createBloxAccounts
so we will pass only indexToRestore and this param will optional (param?)
const index: number = indexToRestore ?? await this.getNextIndex(network);

2021-02-02 09:51 UTC, olegshmuelov commented on app/backend/services/account/account.service.ts
>      const index: number = getNextIndex ? await this.getNextIndex(network) : indexToRestore;
go over all createAccount call and make sure we don't pass getNextIndex anymore

2021-02-02 09:52 UTC, olegshmuelov commented on app/backend/services/account/account.service.ts
> +          await this.createAccount({ getNextIndex: false, indexToRestore: index });
https://github.com/bloxapp/blox-live/pull/101/files#r568464796

2021-02-02 09:52 UTC, olegshmuelov commented on app/backend/services/account/account.service.ts
> +      await this.createAccount({ getNextIndex: false, indexToRestore: index });
https://github.com/bloxapp/blox-live/pull/101/files#r568464796

2021-02-02 09:54 UTC, olegshmuelov commented on app/backend/services/account/account.service.ts
> +      await this.createAccount({ getNextIndex: false, indexToRestore: +lastIndex });
https://github.com/bloxapp/blox-live/pull/101/files#r568464796

2021-02-02 09:56 UTC, olegshmuelov commented on app/backend/services/account/account.service.ts
> +    const accumulate = !!accountsNumber;
accountsNumber rename

2021-02-02 09:57 UTC, olegshmuelov commented on app/backend/services/key-manager/key-manager.service.ts
> +  }
should be removed

2021-02-02 09:58 UTC, olegshmuelov commented on app/backend/services/key-manager/key-manager.service.ts
> +      console.error('KeyManagerService::getAccount error', { command: getAccountCommand, error });
we cant pass getAccountCommand, because its will be saved in the error logs with the sensitive data 
@vadiminc

2021-02-02 09:59 UTC, olegshmuelov commented on app/backend/services/key-manager/key-manager.service.ts
> +      console.error('KeyManagerService::getDepositData error', { command: getDepositDataCommand, error });
we cant pass getAccountCommand, because its will be saved in the error logs with the sensitive data
@vadiminc

2021-02-02 10:04 UTC, olegshmuelov commented on app/components/Test/Test.tsx
> +          await accountService.createAccount({ getNextIndex: false, indexToRestore: 0 });
https://github.com/bloxapp/blox-live/pull/101/files#r568464796

2021-02-02 10:05 UTC, olegshmuelov commented on app/components/Wizard/components/Wallet/CongratulationPage/CongratulationPage.js
> +    setPage(4);
hardcoded?

2021-02-02 10:07 UTC, olegshmuelov commented on app/backend/proccess-manager/account-create.process.ts
> +          }
this fallback action is not right, we can discuss it offline

2021-02-02 10:08 UTC, olegshmuelov requested changes
I reviewed mostly the backend side of this pr.
@nivBlox should review the client side 
@vadiminc pls see my tags

2021-02-02 19:46 UTC, meshin-blox commented on app/backend/proccess-manager/account-create.process.ts
> +          }
This is interesting to discuss, let's talk tomorrow ;0

2021-02-08 14:49 UTC, meshin-blox commented on app/components/Wizard/components/Wallet/CongratulationPage/CongratulationPage.js
> +    setPage(4);
@olegshmuelov in most cases it is hardcoded in all over the app, here it changed because page #4 became create or generate seed screen instead of select network screen and then generate validator screen, both of latest are 4 & 5 accordingly, so page + 1 worked.

2021-02-16 13:14 UTC, olegshmuelov commented on app/backend/proccess-manager/account-create.process.ts
> +    this.fallbackActions[0].actions.unshift(firstAction);
I don't really understand whats happening here
@vadiminc @meshin-blox 
Did you?

2021-02-16 13:20 UTC, olegshmuelov commented on app/backend/services/account/account.service.ts
> +    const index: number = indexToRestore ?? (lastNetworkIndex + 1 || 0);
@meshin-blox 
the 0 here is unnecessary.
can cause a bug in index

2021-02-16 13:26 UTC, olegshmuelov commented on app/backend/services/key-vault/key-vault.service.ts
> +// @CatchClass<KeyVaultService>()
@vadiminc are you sure we don't need to catch key-vault service exceptions?

2021-02-16 13:27 UTC, olegshmuelov commented on app/backend/services/wallet/wallet.service.ts
> +// @CatchClass<WalletService>()
@vadiminc are you sure we don't need to catch key-vault service exceptions?

2021-02-16 13:33 UTC, olegshmuelov commented on app/components/ProcessRunner/useProcessRunner.ts
> +    await dispatch(processSubscribe(name, defaultMessage, credentials, network, indexToRestore));
not sure if there is right way to pass network & indextorestore in start process
only account create process using those params.
have to find another way to pass those params probably in procesPayload generic object/?

2021-02-17 09:03 UTC, meshin-blox commented on app/backend/services/account/account.service.ts
> +    const index: number = indexToRestore ?? (lastNetworkIndex + 1 || 0);
Checking how it works without type spec

2021-02-17 13:37 UTC, meshin-blox commented on app/components/ProcessRunner/useProcessRunner.ts
> +    await dispatch(processSubscribe(name, defaultMessage, credentials, network, indexToRestore));
Yes now I everything except `name` & `defaultMessage` to params object

2021-02-17 14:19 UTC, olegshmuelov approved these changes

2021-02-17 14:42 UTC, merged